language: java
sudo: false

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: s3
  access_key_id: "AKIAJPVTSDOZWPI3EKFA"
  secret_access_key: "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"
  bucket: "S3 Bucket"
